version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: checkapp
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongodb_network

  mongo_setup:
    image: mongo:latest
    container_name: mongo_setup
    depends_on:
      - mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - mongodb_network
    entrypoint: [ "bash", "-c", "sleep 10 && mongo --host mongodb --username root --password rootpassword --authenticationDatabase admin /docker-entrypoint-initdb.d/init-mongo.js" ]

volumes:
  mongodb_data:

networks:
  mongodb_network: